server:
  port: 8080
  servlet:
    context-path: /
    encoding:      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?severTimeZone=Asia/Seoul
    username: cos
    password: cos1234
  mvc:    view:      prefix: /template/
      suffix: .mustache
  jpa:    hibernate:      ddl-auto: update #create update none
      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
  security:    oauth2:      client:        registration:          google:
            client-id: clientId
            client-secret: clientSecret
            scope:            - email
            - profile

          facebook:
            client-id: clientId
            client-secret: clientSecret
            scope:            - email
            - public_profile
            redirect-uri: http://localhost:8080/login/oauth2/code/facebook
            # google, facebook 과 같이 oauth2 client 라이브러리가 제공하는 provider일 경우, ~/login/oauth2/code/{providerName} 이 고정. redirect-uri 생략 가능

          naver:
            client-id: clinetId
            client-secret: clientSecret
            scope:            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            # naver 는 provider가 아니기 때문에 redirect-uri 옵션 값이 필수이며, /login/oauth2/code 를 지키지 않아도 됨, naver API callback Url에 입력 필요.
            
        provider:          naver:                                                        # 네이버는 provider 가 아니기 때문에 사용하기 위해서 반드시 등록 필요
            authorization-uri: https//nid.naver.com/oauth2.0/authorize  # 네이버 로그인 화면
            token-uri: https://nid.naver.com/oauth2.0/token             # 네이버 토큰 리턴 
            user-info-uri: https://openapi.naver.com/v1/nid/me          # 네이버 사용자 정보
            user-name-attribute: response                               # 사용자 정보를 json으로 받는데 response 라는 키 값으로 네이버가 리턴해줌.
            
            